name: Build
on:
  push:
    branches:
      - "master"
      - "github-actions" # dedicated branch for testing GH Actions workflow
  pull_request:
    branches:
      - "master"

jobs:
  build:
    strategy:
      matrix:
        node-version: [14, 16, 18, 19]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build app
        run: yarn build
      - name: Save build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: urban-planning-app-node${{ matrix.node-version }}
          path: dist
